# Generated by Django 5.0 on 2023-12-30 15:43

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_kyc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=account.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to=account.models.user_directory_path),
        ),
    ]
