# Generated by Django 5.0 on 2023-12-30 15:55

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_kyc_identity_image_alter_kyc_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={},
        ),
        migrations.RemoveField(
            model_name='account',
            name='review',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=7, max_length=25, prefix='PEX', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=25, prefix='217', unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_status',
            field=models.CharField(choices=[('in-active', 'In-Active'), ('active', 'Active')], default='in-active', max_length=100),
        ),
        migrations.AlterField(
            model_name='account',
            name='red_code',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh1234567890', length=10, max_length=10, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='fax',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('adhar_card', 'Adhar Card'), ('driving_licience', 'Driving Licence'), ('international_passport', 'Innternational Passport')], max_length=140),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(upload_to='kyc'),
        ),
    ]
